/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("SASaleListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheSASaleList.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheSASaleList.onFilterBar().iCheckFilterField("Partner");
            Then.onTheSASaleList.onFilterBar().iCheckFilterField("Sales Date");
            Then.onTheSASaleList.onFilterBar().iCheckFilterField("Sales Currency");
        });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheSASaleList.onTable().iCheckColumns(11, {"7":{"header":"Difference"},"8":{"header":"Difference (Unit)"},"LineIcon":{"header":"Icon"},"PartnerNumber":{"header":"Partner"},"SalesDate":{"header":"Sales Date"},"SalesYear":{"header":"Sales Year"},"SalesMonth":{"header":"Sales Month"},"SalesVolume":{"header":"Sales Volume"},"SalesCurrency":{"header":"Sales Currency"},"_SASold/MaterialId":{"header":"Material"},"UUID":{"header":"UUID"}});

        });


        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheSASaleList.onFilterBar().iExecuteSearch();
            
            Then.onTheSASaleList.onTable().iCheckRows();

            When.onTheSASaleList.onTable().iPressRow(0);
            Then.onTheSASaleObjectPage.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});