/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("SASaleObjectPageObjectPage journey");

        opaTest("Navigate to SASaleObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheSASaleList.onFilterBar().iExecuteSearch();

            Then.onTheSASaleList.onTable().iCheckRows();
            When.onTheSASaleList.onTable().iPressRow(0);

            Then.onTheSASaleObjectPage.iSeeThisPage();
        });


        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheSASaleObjectPage.iCheckNumberOfSections(7);
            When.onTheSASaleObjectPage.iPressSectionIconTabFilterButton("idGeneral");
            Then.onTheSASaleObjectPage.iCheckSection({ section: "idGeneral" });
            When.onTheSASaleObjectPage.iPressSectionIconTabFilterButton("idDifference");
            Then.onTheSASaleObjectPage.iCheckSection({ section: "idDifference" });
            When.onTheSASaleObjectPage.iPressSectionIconTabFilterButton("idInformation");
            Then.onTheSASaleObjectPage.iCheckSection({ section: "idInformation" });
            When.onTheSASaleObjectPage.iPressSectionIconTabFilterButton("idAdmin");
            Then.onTheSASaleObjectPage.iCheckSection({ section: "idAdmin" });
            When.onTheSASaleObjectPage.iPressSectionIconTabFilterButton("idSASeller");
            Then.onTheSASaleObjectPage.iCheckSection({ section: "idSASeller" });
            When.onTheSASaleObjectPage.iPressSectionIconTabFilterButton("idSASold");
            Then.onTheSASaleObjectPage.iCheckSection({ section: "idSASold" });
            When.onTheSASaleObjectPage.iPressSectionIconTabFilterButton("idSAInfo");
            Then.onTheSASaleObjectPage.iCheckSection({ section: "idSAInfo" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});